booking:
  property: Product Profile Dev
spring:
  data:
    mongodb:
      uri: mongodb+srv://chris:admin@clusterspring.l3fvwng.mongodb.net/productDb?retryWrites=true&w=majority&appName=ClusterSpring
app:
  testProp: Property of test updated